### ISSUE TITLE
Accessing error code from returned error

### ISSUE THREAD

**Issue by bendikro** [solher/arangolite#28]
When performing a `CreateDatabase` where the database already exists, the database returns error code 1207 (https://docs.arangodb.com/3.0/Manual/Appendix/ErrorCodes.html, ERROR_ARANGO_DUPLICATE_NAME).

This error code is wrapped in a [`numberedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L26) at [https://github.com/solher/arangolite/blob/v2.0.1/database.go#L207](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L207)

However, at the next step, the [`numberedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L26) is wrapped in a [`statusCodedError`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L3) at [https://github.com/solher/arangolite/blob/v2.0.1/database.go#L213](https://github.com/solher/arangolite/blob/v2.0.1/database.go#L213)

The `statusCodedError` is what is returned by `Send`.

My question is how should the error code be accessed?

[`HasErrorNum`](https://github.com/solher/arangolite/blob/v2.0.1/errors.go#L36) will not work, since it requires a `numberedError` as input, and casting to `statusCodedError` to access the `error` attribute doesn't work, since `statusCodedError` is not exported.

Current result of `arangolite.HasStatusCode(err)` is 409, but `arangolite.HasErrorNum(e_status, 1207)` gives false.

**Comment by solher** [comment]
Well the answer is quite simple. I just messed up my wrapping :)
Could you try again with the tip? It should be fixed now.
I also added some `GetErrorNum` and `GetStatusCode` functions to allow better debugging.

**Comment by bendikro** [comment]
Hi @solher 

Look at these tests: https://github.com/bendikro/arangolite/blob/master-error-tests/errors_test.go

Are they supposed to pass?

I still don't understand how I can access the error number when the numberedError is wrapped inside a statusCodedError.
